North-Star-AI App Back-up

import asyncio
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio
from typing import TypedDict, Optional, List, Dict, Callable
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage, AIMessage, BaseMessage, SystemMessage
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field
import os
import json
import markdown
import re

from dotenv import load_dotenv

load_dotenv(override=True)

# --- 1. CONFIG & TRANSLATIONS ---

CURRENCY_CONFIG = {
    "THB": {
        "symbol": "฿",
        "name": "Thai Baht",
        "food_name": "ข้าวผัดกระเพรา (Pad Krapao)",
        "food_price": 60,
        "defaults": {
            "current_savings": 100000.0,
            "monthly_savings": 5000.0,
            "target_expense": 30000.0,
            "benchmarks": {"Simple": 20000, "Moderate": 50000, "Luxury": 100000},
            "quick_save": 2000,
            "default_return": 1.5,
            "inflation_rate": 2.5
        },
        "rates": {
            "Bank/Cash": 1.5,
            "Lottery/Omsin": 0.5,
            "Bonds": 1.7,
            "Gold": 4.0,
            "Stocks/Mutual Funds": 7.0,
            "Crypto": 20.0,
            "Blended (Moderate)": 4.25
        }
    },
    "USD": {
        "symbol": "$",
        "name": "US Dollar",
        "food_name": "Big Mac",
        "food_price": 6.20,
        "defaults": {
            "current_savings": 10000.0,
            "monthly_savings": 500.0,
            "target_expense": 4000.0,
            "benchmarks": {"Simple": 2500, "Moderate": 5000, "Luxury": 10000},
            "quick_save": 200,
            "default_return": 4.5,
            "inflation_rate": 3.0
        },
        "rates": {
            "Bank/Cash": 4.5,
            "HYSA/Bonds": 4.3,
            "Gold": 5.0,
            "Stocks/ETF": 9.5,
            "Crypto": 20.0,
            "Blended (Moderate)": 7.0
        }
    }
}

TRANS = {
    "EN": {
        "title": "Let's Plan Together!",
        "api_error": "⚠️ System Error: OPENROUTER_API_KEY not found in environment.",
        "chat_placeholder": "Type your answer here...",
        "chat_welcome": "Hello! 👋 I am your Personal Retirement Coach. \n\nInstead of forms, let's just chat. \n\n**To start, how old are you and when would you like to retire?**",
        "dashboard_btn": "🚀 View My Financial Plan",
        "restart_btn": "Start New Chat",
        "tip_blue_header": "💡 Asset Selection",
        "tip_blue_body": "Keeping cash in a bank might earn **{cash_rate}%**, while stocks could earn **{stock_rate}%**. We adjust your math based on your style.",
        "tip_green_header": "🍔 Inflation Reality",
        "tip_green_body": "Inflation is silent but deadly. A **{food_name}** costing {symbol}{price} today could cost {symbol}{future_price} in 20 years!",
        "tip_yellow_header": "⚡ The Rule of 72",
        "tip_yellow_body": "Want to double your money? Divide 72 by your return rate. At **7% return**, money doubles every **~10 years**!",
        "age": "Age", "retire_age": "Retire Age", "curr_sav": "Current Savings",
        "month_sav": "Monthly Savings", "return_rate": "Exp. Return (%)", 
        "inflation": "Inflation (%)", "growth": "Savings Growth (%)",
        "expense": "Target Monthly Expense", "calc_header": "📊 Your Financial Outlook",
        "krapao_label": "{food_name} Index (Future)",
        "krapao_help": "Estimated price of a {food_name} when you retire.",
        "rate_source": "Rate set to {rate}% based on your style: '{style}'",
        "advice_btn": "💡 Ask Coach for Advice",
        "advice_header": "💬 Career & Investment Strategy",
        "advice_intro": "I can help optimize your plan. To give specific advice, **could you tell me what you do for a living?**",
        "advice_placeholder": "e.g. I am a software engineer...",
        "chat_again_btn": "💬 Back to Main Chat",
        "download_btn": "📥 Download Full Report",
        "sidebar_settings": "Settings",
        "sidebar_profile": "Profile Strength",
        "sidebar_keep_going": "Keep chatting to fill the bar!",
        "sidebar_summary": "Live Profile Data",
        "fine_tune": "🛠️ Fine-tune Assumptions",
        "chart_title": "📈 Wealth Trajectory",
        "metric_safe": "Safe Monthly Income",
        "metric_target": "Target Need",
        "status_success": "🎉 Freedom Achieved!",
        "status_warning": "⚠️ Almost there. Increase savings slightly.",
        "status_danger": "🚨 Action Required. Large gap detected.",
        "quick_fixes": "💡 Quick Fixes",
        "fix_save": "➕ Save +{symbol}{amount}/mo",
        "fix_delay": "⏳ Retire +2 Years",
        "footer_gen": "Generated by AI Retirement Coach",
        "rep_age": "Age",
        "rep_retire_age": "Retirement Age",
        "rep_curr_sav": "Current Savings",
        "rep_month_sav": "Monthly Savings",
        "rep_exp_ret": "Expected Return",
        "rep_inflation": "Inflation",
        "rep_sav_growth": "Savings Growth",
        "rep_safe_inc": "Safe Monthly Income",
        "rep_target_exp": "Target Expense",
        "rep_score": "Readiness Score",
        "rep_krapao": "Future {food_name}",
        "rep_no_advice": "No specific advice requested.",
        "rep_coach_you": "You",
        "rep_coach_ai": "Coach",
        "rep_inv_style": "Investment Style",
        "sel_asset": "Typical Asset Class",
        "nav_header": "Navigation",
        "nav_chat": "📝 Quick Chat",
        "nav_dash": "📊 Dashboard"
    },
    "TH": {
        "title": "มาวางแผนเกษียณกัน!",
        "api_error": "⚠️ ข้อผิดพลาดระบบ: ไม่พบ OPENROUTER_API_KEY ใน Environment",
        "chat_placeholder": "พิมพ์คำตอบที่นี่...",
        "chat_welcome": "สวัสดีครับ! 🙏 ผมคือโค้ชการเงินส่วนตัวของคุณ \n\nไม่ต้องกรอกฟอร์มให้ยุ่งยาก แค่เล่าเรื่องของคุณให้ผมฟัง\n\n**เริ่มจาก... ตอนนี้คุณอายุเท่าไหร่ และอยากเกษียณตอนอายุเท่าไหร่ครับ?**",
        "dashboard_btn": "🚀 ดูแผนการเงินของฉัน",
        "restart_btn": "เริ่มคุยใหม่",
        "tip_blue_header": "💡 ที่เก็บเงินสำคัญไฉน?",
        "tip_blue_body": "ฝากธนาคารอาจได้ดอกเบี้ย **{cash_rate}%** แต่ถ้าลงทุนหุ้นอาจได้ **{stock_rate}%** ระบบจะช่วยประเมินผลตอบแทนตามสไตล์การออมของคุณครับ",
        "tip_green_header": "🍛 เรื่องจริงของเงินเฟ้อ",
        "tip_green_body": "รู้ไหมครับ **{food_name}** ราคา **{symbol}{price}** วันนี้ ในอีก 20 ปีข้างหน้าอาจพุ่งไปถึง **{symbol}{future_price}**!",
        "tip_yellow_header": "⚡ กฎเลข 72",
        "tip_yellow_body": "อยากให้เงินงอกเงยเป็น 2 เท่าต้องใช้เวลากี่ปี? เอา 72 หารด้วยผลตอบแทน ถ้าได้ **7%** เงินจะโต 2 เท่าใน **~10 ปี** เริ่มเร็วได้เปรียบ!",
        "age": "อายุปัจจุบัน", "retire_age": "เกษียณตอนอายุ", "curr_sav": "เงินออมปัจจุบัน",
        "month_sav": "เงินออมต่อเดือน", "return_rate": "ผลตอบแทน (%)", 
        "inflation": "เงินเฟ้อ (%)", "growth": "เงินออมโตปีละ (%)",
        "expense": "รายจ่ายหลังเกษียณต่อเดือน", "calc_header": "📊 ภาพรวมทางการเงินของคุณ",
        "krapao_label": "ดัชนี {food_name} (ในอนาคต)",
        "krapao_help": "ราคา {food_name} 1 จาน ในวันที่คุณเกษียณ (คำนวณจากเงินเฟ้อ)",
        "rate_source": "ปรับผลตอบแทนเป็น {rate}% ตามรูปแบบการออม: '{style}'",
        "advice_btn": "💡 ปรึกษาโค้ชเพิ่มเติม",
        "advice_header": "💬 คำแนะนำอาชีพและการลงทุน",
        "advice_intro": "ผมช่วยแนะนำวิธีไปถึงเป้าหมายได้ครับ เพื่อความแม่นยำ **ช่วยบอกหน่อยครับว่าทำอาชีพอะไร?**",
        "advice_placeholder": "เช่น เป็นพนักงานบริษัทเอกชน...",
        "chat_again_btn": "💬 กลับไปคุยกับโค้ชหลัก",
        "download_btn": "📥 ดาวน์โหลดรายงานฉบับเต็ม",
        "sidebar_settings": "ตั้งค่า",
        "sidebar_profile": "ความสมบูรณ์ของข้อมูล",
        "sidebar_keep_going": "คุยต่อนะครับ กราฟใกล้เต็มแล้ว!",
        "sidebar_summary": "ข้อมูลปัจจุบัน",
        "fine_tune": "🛠️ ปรับตัวแปรสมมติฐาน",
        "chart_title": "📈 เส้นทางสู่ความมั่งคั่ง",
        "metric_safe": "รายได้ที่ใช้ได้จริง (ต่อเดือน)",
        "metric_target": "เป้าหมายรายจ่าย",
        "status_success": "🎉 ยินดีด้วย! คุณมีอิสรภาพทางการเงินแล้ว",
        "status_warning": "⚠️ เกือบถึงแล้ว! ลองออมเพิ่มอีกนิด",
        "status_danger": "🚨 ต้องรีบปรับแผน! ช่องว่างยังห่างอยู่",
        "quick_fixes": "💡 ทางลัดแก้เกม",
        "fix_save": "➕ ออมเพิ่ม {amount}",
        "fix_delay": "⏳ เกษียณช้าลง 2 ปี",
        "footer_gen": "สร้างโดย AI วางแผนเกษียณ",
        "rep_age": "อายุปัจจุบัน",
        "rep_retire_age": "อายุเกษียณ",
        "rep_curr_sav": "เงินออมปัจจุบัน",
        "rep_month_sav": "เงินออมต่อเดือน",
        "rep_exp_ret": "ผลตอบแทนคาดหวัง",
        "rep_inflation": "อัตราเงินเฟ้อ",
        "rep_sav_growth": "การเติบโตเงินออม",
        "rep_safe_inc": "รายได้ที่ใช้ได้จริง",
        "rep_target_exp": "รายจ่ายเป้าหมาย",
        "rep_score": "คะแนนความพร้อม",
        "rep_krapao": "ราคา {food_name} ในอนาคต",
        "rep_no_advice": "ยังไม่มีการขอคำแนะนำเพิ่มเติม",
        "rep_coach_you": "คุณ",
        "rep_coach_ai": "โค้ช",
        "rep_inv_style": "รูปแบบการลงทุน",
        "sel_asset": "สินทรัพย์ที่ลงทุน",
        "nav_header": "เมนูหลัก",
        "nav_chat": "📝 สัมภาษณ์",
        "nav_dash": "📊 ผลวิเคราะห์"
    }
}

# --- 2. STRUCTURED OUTPUT MODEL ---

class UserProfile(BaseModel):
    age: Optional[int] = Field(None, description="Current age of the user")
    retirement_age: Optional[int] = Field(None, description="Target retirement age")
    current_savings: Optional[float] = Field(None, description="Total current assets/savings")
    monthly_savings: Optional[float] = Field(None, description="Amount saved/invested per month")
    target_monthly_expense: Optional[float] = Field(None, description="Target monthly spending in retirement")
    investment_style: Optional[str] = Field(None, description="How they store money (e.g. Bank, Gold, Stocks, Lottery)")
    inferred_return_rate: Optional[float] = Field(None, description="Estimated return rate based on investment style")
    
    def get_completion_percentage(self):
        fields = [self.age, self.retirement_age, self.current_savings, self.monthly_savings, self.target_monthly_expense, self.investment_style]
        filled = len([f for f in fields if f is not None])
        return int((filled / 6) * 100)

    def is_complete(self):
        return self.get_completion_percentage() == 100

# --- 3. INTERVIEW AGENT (Chat Logic) ---

class InterviewState(TypedDict):
    messages: List[BaseMessage]
    profile: Dict 
    language: str
    currency: str
    is_complete: bool


def _missing_profile_fields(profile: Dict) -> List[str]:
    missing = []
    if not profile.get("age"): missing.append("Current Age")
    if not profile.get("retirement_age"): missing.append("Target Retirement Age")
    if profile.get("current_savings") is None: missing.append("Current Savings")
    if profile.get("monthly_savings") is None: missing.append("Monthly Savings")
    if profile.get("target_monthly_expense") is None: missing.append("Desired Retirement Lifestyle")
    if not profile.get("investment_style"): missing.append("Where they store money/Investment Style")
    return missing


def build_interviewer_prompt(profile: Dict, lang: str, currency: str) -> str:
    missing = _missing_profile_fields(profile)
    missing_str = ", ".join(missing)
    curr_conf = CURRENCY_CONFIG[currency]
    b = curr_conf["defaults"]["benchmarks"]
    s, m, l = b["Simple"], b["Moderate"], b["Luxury"]
    sym = curr_conf["symbol"]

    benchmarks_str = f"(Tip: Suggest Simple ~{sym}{s:,}, Moderate ~{sym}{m:,}, Luxury ~{sym}{l:,})" if "Desired Retirement Lifestyle" in missing else ""
    inv_tip = "(Tip: Ask if they keep in Bank, Gold, Stocks, or Savings Lottery)" if "Where they store money/Investment Style" in missing else ""
    lang_name = "Thai" if lang == "TH" else "English"

    return f"""
    You are a friendly Retirement Coach.
    Language: {lang_name}.
    Currency Context: {currency} ({sym}).
    Missing Data: [{missing_str}]
    Known Data: {profile}
    
    Rules:
    1. Ask ONE short question to get the missing data.
    2. Be encouraging.
    3. {benchmarks_str}
    4. {inv_tip}
    5. If ALL data present, output ONLY: "CALCULATION_READY"
    """


def _chunk_content_text(chunk) -> str:
    if chunk is None:
        return ""
    content = getattr(chunk, "content", "") or ""
    if isinstance(content, list):
        pieces = []
        for part in content:
            if isinstance(part, dict) and "text" in part:
                pieces.append(part["text"])
            else:
                pieces.append(str(part))
        return "".join(pieces)
    return content


async def stream_chat_response(llm, messages: List[BaseMessage], on_token: Optional[Callable[[str, str], None]] = None) -> str:
    """Stream chunks from the LLM, calling on_token with (delta, full_text)."""
    full_text = ""
    async for chunk in llm.astream(messages):
        delta = _chunk_content_text(chunk)
        if not delta:
            continue
        full_text += delta
        if on_token:
            on_token(delta, full_text)
    return full_text

def extraction_node(state: InterviewState):
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key: return state

    currency = state.get("currency", "THB")
    curr_conf = CURRENCY_CONFIG[currency]
    rates_guide = json.dumps(curr_conf["rates"], ensure_ascii=False, indent=2)
    
    llm = ChatOpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
        model="mistralai/ministral-14b-2512",
        temperature=0
    )
    
    structured_llm = llm.with_structured_output(UserProfile)
    
    benchmarks_str = json.dumps(curr_conf["defaults"]["benchmarks"])
    
    sys_msg = SystemMessage(content=f"""
    Extract user financial profile.
    CURRENCY CONTEXT: {currency} ({curr_conf['symbol']}).
    
    LIFESTYLE BENCHMARKS (For Target Expense): {benchmarks_str}
    
    INVESTMENT RETURN RATE LOGIC:
    You must estimate 'inferred_return_rate' based on the user's description.
    
    REFERENCE RATES (Annualized):
    {rates_guide}
    
    RULES FOR RATE ESTIMATION:
    1. Single Asset: If user says "Bank", use {curr_conf['rates'].get('Bank/Cash')}. If "Stocks", use {curr_conf['rates'].get('Stocks/Mutual Funds')}.
    2. Mixed Assets: If user says "Half gold, half bank", calculate the average.
    3. Ambiguous: If they just say "I save money" without specifying where, use the 'Blended (Moderate)' rate.
    4. Lottery/Omsin: Treat as very low return ({curr_conf['rates'].get('Lottery/Omsin')}).
    5. Crypto: Cap at {curr_conf['rates'].get('Crypto')} even if they claim higher.
    
    If specific number given (e.g. "I get 8% dividend"), use that value.
    """)
    
    try:
        extracted_profile = structured_llm.invoke([sys_msg] + state["messages"])
        current_data = state.get("profile", {}) or {}
        new_data = extracted_profile.model_dump(exclude_none=True)
        merged_data = {**current_data, **new_data}
        
        required = ['age', 'retirement_age', 'current_savings', 'monthly_savings', 'target_monthly_expense', 'investment_style']
        is_complete = all(k in merged_data and merged_data[k] is not None for k in required)
            
        return {"profile": merged_data, "is_complete": is_complete}
        
    except Exception as e:
        return state

def conversational_node(state: InterviewState):
    api_key = os.environ.get("OPENROUTER_API_KEY")
    profile = state.get("profile", {})
    lang = state["language"]
    currency = state.get("currency", "THB")
    
    if state["is_complete"]:
        return {"messages": [AIMessage(content="CALCULATION_READY")]}

    llm = ChatOpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
        model="x-ai/grok-4.1-fast",
        temperature=0.7
    )
    system_prompt = build_interviewer_prompt(profile, lang, currency)
    response = llm.invoke([SystemMessage(content=system_prompt)] + state["messages"])
    return {"messages": [response]}

def build_interview_graph():
    workflow = StateGraph(InterviewState)
    workflow.add_node("extractor", extraction_node)
    workflow.add_node("interviewer", conversational_node)
    workflow.set_entry_point("extractor")
    workflow.add_edge("extractor", "interviewer")
    workflow.add_edge("interviewer", END)
    return workflow.compile()

# --- 4. VISUALIZATION LOGIC ---

def calculate_projection(age, retire_age, current, monthly, rate, inflation, growth, currency):
    data = []
    balance = current
    monthly_inv = monthly
    years = int(retire_age - age)
    
    food_price = CURRENCY_CONFIG[currency]["food_price"]
    
    if years < 0: years = 0

    for i in range(years + 1):
        real_val = balance / ((1 + inflation/100)**i)
        future_food = food_price * ((1 + inflation/100)**i)
        
        data.append({
            "Age": age + i, 
            "Nominal": balance, 
            "Real": real_val,
            "FoodPrice": future_food
        })
        
        balance += (balance * (rate/100)) + (monthly_inv * 12)
        monthly_inv *= (1 + growth/100)
        
    return pd.DataFrame(data)

def create_chart(df, target_monthly, currency):
    symbol = CURRENCY_CONFIG[currency]["symbol"]
    target_pv = (target_monthly * 12) / 0.04 
    
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df["Age"], y=df["Real"], 
        fill='tozeroy', 
        name='Real Purchasing Power (Inflation Adj.)', 
        line=dict(color='#00CC96', width=3),
        hovertemplate=f"Age %{{x}}: {symbol}%{{y:,.0f}}<extra></extra>"
    ))
    fig.add_trace(go.Scatter(
        x=df["Age"], y=df["Nominal"], 
        name='Nominal Amount', 
        line=dict(dash='dot', color='#B8F7D4'),
        hovertemplate=f"Nominal: {symbol}%{{y:,.0f}}<extra></extra>"
    ))
    fig.add_hline(y=target_pv, line_dash="dash", line_color="#EF553B", annotation_text="Freedom Line")
    
    fig.update_layout(
        height=400, 
        margin=dict(l=60,r=20,t=40,b=20), 
        hovermode="x unified",
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    fig.update_yaxes(automargin=True)
    
    return fig

def create_gauge(score, t):
    color = "red" if score < 50 else "#FFC107" if score < 80 else "#00CC96"
    
    fig = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = score,
        title = {'text': t['rep_score']},
        gauge = {
            'axis': {'range': [None, 100]},
            'bar': {'color': color},
            'steps': [
                {'range': [0, 50], 'color': "rgba(255, 0, 0, 0.1)"},
                {'range': [50, 80], 'color': "rgba(255, 193, 7, 0.1)"},
                {'range': [80, 100], 'color': "rgba(0, 204, 150, 0.1)"}
            ],
        }
    ))
    fig.update_layout(height=250, margin=dict(l=20,r=20,t=30,b=20))
    return fig

# --- 5. ADVICE AGENT LOGIC ---
def build_advice_prompt(profile, language, currency):
    lang_name = "Thai" if language == "TH" else "English"
    conf = CURRENCY_CONFIG[currency]
    sym = conf["symbol"]
    gap = profile.get('monthly_shortfall_gap', 0)
    gap_str = f"{sym}{gap:,.0f}"
    rates_str = json.dumps(conf["rates"], ensure_ascii=False)

    return f"""
    You are a Wise Financial Coach.
    Language: {lang_name}
    Currency: {currency} (Rates: {rates_str})
    User Profile Data: {profile}
    
    CRITICAL OBJECTIVE:
    The user has a monthly retirement shortfall of {gap_str}. 
    To give accurate advice, you MUST know these 3 things about the user:
    1. Current Job & Income Stability.
    2. Current Debt Load (Credit cards, loans, etc).
    3. Expertise & Hobbies (To suggest specific side-hustles or upskilling).

    INSTRUCTIONS:
    1. REVIEW the conversation history below.
    2. CHECK: Has the user provided the 3 pieces of info above?
    
    [SCENARIO A: Information is Missing]
    If any of the 3 items are missing or vague, DO NOT give the full financial plan yet.
    Instead, ask the user polite, conversational questions to gather the missing details. 
    You can ask for 1 or 2 items at a time. Do not overwhelm them.
    
    [SCENARIO B: Information is Sufficient]
    Only when you have a clear picture of their Job, Debt, and Skills, provide the Final Advice Plan.
    
    The Final Advice Plan must:
    1. Acknowledge the {gap_str} gap.
    2. Analyze their current investment style ({profile.get('investment_style', 'Unknown')}) and suggest specific allocation changes based on the gathered info.
    3. Suggest a specific side-hustle or career move based on their *Expertise/Hobbies* you just learned.
    4. Address their debt strategy if they mentioned debt.
    
    Keep the tone encouraging, professional, and concise.
    """


def get_advice(profile, chat_history, language, currency):
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key: 
        return "Configuration Error: API Key missing."

    llm = ChatOpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
        model="x-ai/grok-4.1-fast",
        temperature=0.7
    )

    system_prompt = build_advice_prompt(profile, language, currency)
    messages = [SystemMessage(content=system_prompt)] + chat_history
    response = llm.invoke(messages)
    return response.content


async def stream_advice(profile, chat_history, language, currency, on_token: Optional[Callable[[str, str], None]] = None):
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        if on_token:
            on_token("", "Configuration Error: API Key missing.")
        return "Configuration Error: API Key missing."

    llm = ChatOpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
        model="x-ai/grok-4.1-fast",
        temperature=0.7,
        streaming=True
    )

    system_prompt = build_advice_prompt(profile, language, currency)
    messages = [SystemMessage(content=system_prompt)] + chat_history
    return await stream_chat_response(llm, messages, on_token=on_token)

# --- 6. REPORT GENERATION & FIXES ---

# Normalize LLM markdown so python-markdown can render tables and lists reliably.
def clean_markdown_table(text: str) -> str:
    if not text:
        return ""

    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Unwrap fenced code blocks that may contain markdown tables
    fence_pattern = r"```(?:[a-zA-Z0-9_]+)?\n([\s\S]*?)```"
    text = re.sub(fence_pattern, r"\1", text)

    lines = text.split("\n")
    fixed_lines = []
    inside_table = False
    for line in lines:
        prev_inside_table = inside_table
        is_table_row = line.lstrip().startswith("|")
        if is_table_row and not inside_table and fixed_lines:
            prev_line = fixed_lines[-1]
            if prev_line.strip() != "":
                # Add at least one spacer; if coming right after a list item, add two to break the list.
                fixed_lines.append("")
                if re.match(r"^\s*[-*+]\s", prev_line):
                    fixed_lines.append("")
        # If we are leaving a table, add a spacer so following text doesn't join as a row.
        if prev_inside_table and not is_table_row and fixed_lines and fixed_lines[-1] != "":
            fixed_lines.append("")
        fixed_lines.append(line)
        inside_table = is_table_row
        if not is_table_row:
            inside_table = False

    text = "\n".join(fixed_lines)

    # Fix cases where header and separator are merged on one line
    text = re.sub(r"(\|[^\n]+\|)\s*(\|\s*[-:]+[^\n]*)", r"\1\n\2", text)

    return text

def generate_html_report(profile, assumptions, safe_income, target_expense, food_price, score, advice_history, fig, lang, currency):
    t = TRANS[lang]
    conf = CURRENCY_CONFIG[currency]
    sym = conf["symbol"]
    food_name = conf["food_name"]
    
    t_header = "Financial Freedom Report" if lang == "EN" else "รายงานแผนเกษียณอายุ"
    t_date = "Date Generated" if lang == "EN" else "วันที่สร้างรายงาน"
    t_profile = "Profile Summary" if lang == "EN" else "ข้อมูลส่วนตัว"
    t_assumptions = "Assumptions" if lang == "EN" else "สมมติฐานการคำนวณ"
    t_metrics = "Key Metrics" if lang == "EN" else "ตัวเลขสำคัญ"
    t_advice = "Coach Suggestions" if lang == "EN" else "คำแนะนำจากโค้ช"
    t_chart = "Wealth Projection" if lang == "EN" else "กราฟแสดงความมั่งคั่ง"
    
    t_food_label = t['rep_krapao'].format(food_name=food_name)

    chart_html = pio.to_html(fig, full_html=False, include_plotlyjs='cdn')
    
    advice_html = ""
    if advice_history:
        for msg in advice_history:
            if isinstance(msg, SystemMessage):
                continue 
            
            bg_color = "#e3f2fd" if isinstance(msg, HumanMessage) else "#f0f2f6"
            role_name = t["rep_coach_you"] if isinstance(msg, HumanMessage) else t["rep_coach_ai"]
            
            try:
                raw_content = msg.content if isinstance(msg.content, str) else str(msg.content)
                clean_content = clean_markdown_table(raw_content)
                msg_content = markdown.markdown(clean_content, extensions=['extra', 'sane_lists'])
            except Exception:
                msg_content = msg.content
            
            advice_html += f"""
            <div style="margin-bottom: 10px; padding: 10px; background-color: {bg_color}; border-radius: 8px;">
                <div style="font-weight: bold; margin-bottom: 4px;">{role_name}</div>
                <div class="chat-content">{msg_content}</div>
            </div>
            """
    else:
        advice_html = f"<p>{t['rep_no_advice']}</p>"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>{t_header}</title>
        <link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@400;700&display=swap" rel="stylesheet">
        <style>
            body {{ font-family: 'Sarabun', sans-serif; max-width: 900px; margin: auto; padding: 40px; color: #333; line-height: 1.6; }}
            h1, h2 {{ color: #00CC96; }}
            h1 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            
            .metric-container {{ display: flex; gap: 20px; margin-bottom: 30px; }}
            .metric-box {{ flex: 1; padding: 20px; background: #f9f9f9; border-radius: 8px; border: 1px solid #eee; text-align: center; }}
            .metric-label {{ font-size: 0.9em; color: #666; margin-bottom: 5px; }}
            .metric-val {{ font-size: 1.5em; font-weight: bold; color: #333; }}
            .profile-grid {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; background: #fff; border: 1px solid #eee; padding: 20px; border-radius: 8px; }}
            .profile-item {{ margin-bottom: 5px; }}
            .chart-container {{ margin: 30px 0; border: 1px solid #eee; padding: 10px; border-radius: 8px; }}
            
            .chat-content p {{ margin: 0 0 8px 0; }}
            .chat-content ul, .chat-content ol {{ margin: 0 0 10px 0; padding-left: 20px; }}
            
            /* Enhanced Table Styling */
            .chat-content table {{
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
                font-size: 0.95em;
                background-color: #ffffff;
                border: 1px solid #ddd;
            }}
            .chat-content th, .chat-content td {{
                border: 1px solid #ddd;
                padding: 10px;
                text-align: left;
            }}
            .chat-content th {{
                background-color: #00CC96;
                color: white;
                font-weight: bold;
                border-bottom: 2px solid #00aa7d;
            }}
            .chat-content tr:nth-child(even) {{
                background-color: #f8f9fa;
            }}
            .chat-content tr:hover {{
                background-color: #f1f1f1;
            }}
        </style>
    </head>
    <body>
        <h1>🐘 {t_header}</h1>
        <p><strong>{t_date}:</strong> {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}</p>
        
        <h2>{t_profile}</h2>
        <div class="profile-grid">
            <div class="profile-item"><strong>{t['rep_age']}:</strong> {profile.get('age')}</div>
            <div class="profile-item"><strong>{t['rep_retire_age']}:</strong> {profile.get('retirement_age')}</div>
            <div class="profile-item"><strong>{t['rep_curr_sav']}:</strong> {sym}{profile.get('current_savings'):,.0f}</div>
            <div class="profile-item"><strong>{t['rep_month_sav']}:</strong> {sym}{profile.get('monthly_savings'):,.0f}</div>
            <div class="profile-item"><strong>{t['rep_inv_style']}:</strong> {profile.get('investment_style')}</div>
        </div>

        <h2>{t_assumptions}</h2>
        <div class="profile-grid">
            <div class="profile-item"><strong>{t['rep_exp_ret']}:</strong> {assumptions.get('rate')}%</div>
            <div class="profile-item"><strong>{t['rep_inflation']}:</strong> {assumptions.get('inflation')}%</div>
            <div class="profile-item"><strong>{t['rep_sav_growth']}:</strong> {assumptions.get('growth')}%</div>
        </div>

        <h2>{t_metrics}</h2>
        <div class="metric-container">
            <div class="metric-box">
                <div class="metric-label">{t['rep_safe_inc']}</div>
                <div class="metric-val">{sym}{safe_income:,.0f}</div>
            </div>
            <div class="metric-box">
                <div class="metric-label">{t['rep_target_exp']}</div>
                <div class="metric-val">{sym}{target_expense:,.0f}</div>
            </div>
            <div class="metric-box">
                <div class="metric-label">{t['rep_score']}</div>
                <div class="metric-val">{score}/100</div>
            </div>
            <div class="metric-box">
                <div class="metric-label">{t_food_label}</div>
                <div class="metric-val">{sym}{food_price:.2f}</div>
            </div>
        </div>
        
        <h2>{t_chart}</h2>
        <div class="chart-container">
            {chart_html}
        </div>
        
        <h2>{t_advice}</h2>
        {advice_html}
        
        <div style="margin-top: 50px; text-align: center; font-size: 0.8em; color: #999;">
            {t['footer_gen']}
        </div>
    </body>
    </html>
    """
    return html

# --- 7. STREAMLIT UI ---

st.set_page_config(page_title="North Star", page_icon="✴️", layout="wide")

st.markdown("""
<style>
    .stButton button {
        border-radius: 12px;
        font-weight: 600;
        transition: all 0.3s ease;
    }
    .stButton button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    [data-testid="stMetricValue"] {
        font-size: 1.8rem !important;
    }
    [data-testid="stChatMessageContent"] {
        background-color: var(--secondary-background-color); 
        border: 1px solid rgba(128, 128, 128, 0.2); 
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);
        border-radius: 16px;
        padding: 1.2rem;
        backdrop-filter: brightness(1.02);
    }
    [data-testid="stChatMessage"] {
        background-color: transparent !important;
        padding: 1rem 0;
    }
    section[data-testid="stSidebar"] {
        background-color: #f8f9fa;
        border-right: 1px solid #eee;
    }
    .sidebar-header {
        text-align: center;
        margin-bottom: 20px;
        padding-bottom: 20px;
        border-bottom: 1px solid #ddd;
    }
    .sidebar-header h1 {
        color: #3bd294;
        font-size: 2rem;
        margin-bottom: 0;
    }
    .sidebar-header p {
        color: #666;
        font-size: 0.9rem;
    }
</style>
""", unsafe_allow_html=True)


if "messages" not in st.session_state: st.session_state["messages"] = []
if "user_profile" not in st.session_state: st.session_state["user_profile"] = {}
if "onboarding_complete" not in st.session_state: st.session_state["onboarding_complete"] = False
if "current_lang" not in st.session_state: st.session_state["current_lang"] = "TH"
if "current_currency" not in st.session_state: st.session_state["current_currency"] = "THB"
if "advice_messages" not in st.session_state: st.session_state["advice_messages"] = []
if "show_advice" not in st.session_state: st.session_state["show_advice"] = False

with st.sidebar:
    st.markdown("""
    <div class="sidebar-header">
        <h1>✴️ North Star</h1>
        <p>AI Retirement Architect</p>
    </div>
    """, unsafe_allow_html=True)
    
    lang_val = st.session_state["current_lang"]
    t = TRANS[lang_val]

    if st.button(f"✨ {t['restart_btn']}", type="primary", use_container_width=True):
        st.session_state["messages"] = []
        st.session_state["advice_messages"] = []
        st.session_state["user_profile"] = {}
        st.session_state["onboarding_complete"] = False
        st.session_state["show_advice"] = False
        st.rerun()

    st.markdown("---")

    st.markdown(f"**{t['nav_header']}**")
    has_data = len(st.session_state["user_profile"]) > 0
    is_dashboard = st.session_state["onboarding_complete"]

    if st.button(t['nav_chat'], use_container_width=True, disabled=not is_dashboard):
        st.session_state["onboarding_complete"] = False
        st.rerun()

    if st.button(t['nav_dash'], use_container_width=True, disabled=is_dashboard):
        st.session_state["onboarding_complete"] = True
        st.rerun()

    st.markdown("---")

    if not st.session_state["onboarding_complete"]:
        p_obj = UserProfile(**st.session_state["user_profile"])
        progress = p_obj.get_completion_percentage()
        st.markdown(f"<br><small>{t['sidebar_profile']}</small>", unsafe_allow_html=True)
        st.progress(progress)
    
    if st.session_state["user_profile"]:
        with st.expander(t["sidebar_summary"], expanded=False):
            st.json(st.session_state["user_profile"])

    with st.expander(t["sidebar_settings"], expanded=False):
        col_s1, col_s2 = st.columns(2)
        lang = col_s1.radio("Lang", ["TH", "EN"], horizontal=False, index=0 if lang_val == "TH" else 1)
        currency = col_s2.radio("Currency", ["THB", "USD"], horizontal=False, index=0 if st.session_state["current_currency"] == "THB" else 1)
        
        if lang != st.session_state["current_lang"] or currency != st.session_state["current_currency"]:
            st.session_state["current_lang"] = lang
            st.session_state["current_currency"] = currency
            st.session_state["messages"] = [] 
            st.session_state["advice_messages"] = []
            st.rerun()

if not os.environ.get("OPENROUTER_API_KEY"):
    st.error(TRANS[st.session_state["current_lang"]]["api_error"])
    st.stop()

curr_conf = CURRENCY_CONFIG[st.session_state["current_currency"]]

if not st.session_state["onboarding_complete"]:
    col_c1, col_c2 = st.columns([2, 1])
    
    with col_c1:
        st.title(t["title"])
        
        if not st.session_state["messages"]:
            st.session_state["messages"].append(AIMessage(content=t["chat_welcome"]))
        
        for msg in st.session_state["messages"]:
            role = "user" if isinstance(msg, HumanMessage) else "assistant"
            with st.chat_message(role):
                st.write(msg.content)
                
        if prompt := st.chat_input(t["chat_placeholder"]):
            st.session_state["messages"].append(HumanMessage(content=prompt))
            with st.chat_message("user"): st.write(prompt)
            
            state_inputs = {
                "messages": st.session_state["messages"], 
                "profile": st.session_state["user_profile"],
                "language": lang,
                "currency": currency,
                "is_complete": False
            }
            
            result = extraction_node(state_inputs)
            st.session_state["user_profile"] = result.get("profile", st.session_state["user_profile"])
            if result.get("is_complete"):
                st.session_state["onboarding_complete"] = True
                st.rerun()

            llm = ChatOpenAI(
                base_url="https://openrouter.ai/api/v1",
                api_key=os.environ.get("OPENROUTER_API_KEY"),
                model="x-ai/grok-4.1-fast",
                temperature=0.7,
                streaming=True
            )
            prompt_text = build_interviewer_prompt(st.session_state["user_profile"], lang, currency)

            assistant_container = st.chat_message("assistant")
            stream_placeholder = assistant_container.empty()

            async def _run_stream():
                return await stream_chat_response(
                    llm,
                    [SystemMessage(content=prompt_text)] + st.session_state["messages"],
                    on_token=lambda _delta, full: stream_placeholder.write(full),
                )

            content = asyncio.run(_run_stream())

            if "CALCULATION_READY" in content:
                st.session_state["onboarding_complete"] = True
                st.rerun()

            st.session_state["messages"].append(AIMessage(content=content))
            st.rerun()

    with col_c2:
        rates_d = curr_conf["rates"]
        sym = curr_conf["symbol"]
        # Escape dollar sign to avoid Streamlit Markdown interpreting it as LaTeX math
        sym_md = sym.replace("$", "\\$") if sym else sym
        
        tip_blue = t["tip_blue_body"].format(
            cash_rate=rates_d.get("Bank/Cash", 1.5),
            stock_rate=rates_d.get("Stocks/Mutual Funds", 7.0) if st.session_state["current_currency"] == "THB" else rates_d.get("Stocks/ETF", 9.5)
        )
        st.info(f"**{t['tip_blue_header']}**\n\n{tip_blue}")
        
        f_name = curr_conf["food_name"]
        f_price = curr_conf["food_price"]
        inf_rate = curr_conf["defaults"]["inflation_rate"]
        f_future = f_price * ((1 + inf_rate/100) ** 20)
        
        tip_green = t["tip_green_body"].format(
            food_name=f_name,
            symbol=sym_md,
            price=f"{f_price:.0f}" if f_price > 10 else f"{f_price:.2f}",
            future_price=f"{f_future:.0f}" if f_future > 10 else f"{f_future:.2f}"
        )
        st.success(f"**{t['tip_green_header']}**\n\n{tip_green}")
        
        tip_yellow = t["tip_yellow_body"]
        st.warning(f"**{t['tip_yellow_header']}**\n\n{tip_yellow}")
        
        if st.session_state["user_profile"]:
            st.markdown("---")
            if st.button(t["dashboard_btn"], type="primary", use_container_width=True):
                st.session_state["onboarding_complete"] = True
                st.rerun()

else:
    p = st.session_state["user_profile"]
    curr_conf = CURRENCY_CONFIG[st.session_state["current_currency"]]
    sym = curr_conf["symbol"]
    defaults = curr_conf["defaults"]
    
    def_age = int(p.get("age", 30))
    def_retire = int(p.get("retirement_age", 60))
    def_curr = float(p.get("current_savings") or defaults["current_savings"])
    def_month = float(p.get("monthly_savings") or defaults["monthly_savings"])
    def_target = float(p.get("target_monthly_expense") or defaults["target_expense"])
    
    inferred_rate = p.get("inferred_return_rate")
    if inferred_rate is None:
        inferred_rate = defaults["default_return"]
        
    inv_style = p.get("investment_style", "Standard")

    st.markdown(f"## {t['calc_header']}")
    
    with st.container():
        c1, c2, c3, c4 = st.columns(4)
        age = c1.number_input(t["age"], 20, 90, def_age)
        retire_age = c2.number_input(t["retire_age"], age+1, 100, def_retire)
        
        money_step = 1000.0 if st.session_state["current_currency"] == "THB" else 100.0
        
        curr_sav = c3.number_input(f"{t['curr_sav']} ({sym})", 0.0, None, def_curr, step=money_step*10)
        month_sav = c4.number_input(f"{t['month_sav']} ({sym})", 0.0, None, def_month, step=money_step)
        
        with st.expander(t["fine_tune"], expanded=True):
            rc1, rc2, rc3 = st.columns(3)
            
            rates_map = curr_conf["rates"]
            asset_options = list(rates_map.keys())
            
            default_idx = 0
            if inferred_rate:
                closest_asset = min(rates_map.items(), key=lambda x: abs(x[1] - inferred_rate))
                if closest_asset[0] in asset_options:
                     default_idx = asset_options.index(closest_asset[0])
            
            selected_asset = rc1.selectbox(
                t["sel_asset"],
                options=asset_options,
                index=default_idx
            )
            
            suggested_rate_val = rates_map[selected_asset]
            
            rate = rc1.slider(t["return_rate"], 1.0, 20.0, float(suggested_rate_val))
            
            rc1.caption(f"Benchmark: {selected_asset} (~{suggested_rate_val}%)")
            
            inflation = rc2.slider(t["inflation"], 0.0, 10.0, float(defaults["inflation_rate"]))
            growth = rc3.slider(t["growth"], 0.0, 20.0, 3.0)
            target_expense = st.number_input(f"{t['expense']} ({sym})", 0.0, None, def_target, step=money_step)

    df = calculate_projection(age, retire_age, curr_sav, month_sav, rate, inflation, growth, st.session_state["current_currency"])
    
    final_real = df.iloc[-1]["Real"]
    safe_income = (final_real * 0.04) / 12
    gap = safe_income - target_expense
    score = min(100, max(0, int((safe_income / target_expense) * 100)))
    
    future_food = df.iloc[-1]["FoodPrice"]
    food_label = t["krapao_label"].format(food_name=curr_conf["food_name"])
    food_help = t["krapao_help"].format(food_name=curr_conf["food_name"])
    
    st.divider()
    
    col_viz, col_gauge = st.columns([2, 1])
    
    main_fig = create_chart(df, target_expense, st.session_state["current_currency"])
    
    with col_viz:
        st.markdown(f"### {t['chart_title']}")
        st.plotly_chart(main_fig, width='content')
        
        mc1, mc2, mc3 = st.columns(3)
        mc1.metric(t["metric_safe"], f"{sym}{safe_income:,.0f}", help="Based on 4% withdrawal rule")
        mc2.metric(t["metric_target"], f"{sym}{target_expense:,.0f}")
        
        multiplier = future_food / curr_conf["food_price"]
        mc3.metric(food_label, f"{sym}{future_food:.2f}", delta=f"Price x{multiplier:.1f}", delta_color="inverse", help=food_help)

    with col_gauge:
        st.plotly_chart(create_gauge(score, t), width='content')
        
        if score >= 100:
            st.success(t["status_success"])
        elif score > 80:
            st.warning(t["status_warning"])
        else:
            st.error(t["status_danger"])
            
        st.markdown(f"#### {t['quick_fixes']}")
        
        qs_amt = defaults["quick_save"]
        fix_save_label = t["fix_save"].format(symbol=sym, amount=f"{qs_amt:,}")
        
        if st.button(fix_save_label, use_container_width=True):
            p["monthly_savings"] = month_sav + qs_amt
            st.session_state["user_profile"] = p
            st.rerun()
        if st.button(t["fix_delay"], use_container_width=True):
            p["retirement_age"] = retire_age + 2
            st.session_state["user_profile"] = p
            st.rerun()
            
        st.markdown("---")
        if not st.session_state["show_advice"]:
            if st.button(t["advice_btn"], type="primary", use_container_width=True):
                st.session_state["show_advice"] = True
                if not st.session_state["advice_messages"]:
                    st.session_state["advice_messages"].append(AIMessage(content=t["advice_intro"]))
                st.rerun()

    if st.session_state["show_advice"]:
        st.markdown("---")
        st.markdown(f"### {t['advice_header']}")
        
        advice_container = st.container()
        
        with advice_container:
            for msg in st.session_state["advice_messages"]:
                role = "user" if isinstance(msg, HumanMessage) else "assistant"
                with st.chat_message(role):
                    st.write(msg.content)
                    
        if advice_input := st.chat_input(t["advice_placeholder"]):
            st.session_state["advice_messages"].append(HumanMessage(content=advice_input))
            with st.chat_message("user"):
                st.write(advice_input)
            
            current_stats = {
                "age": age, 
                "retirement_age": retire_age,
                "current_savings": curr_sav, 
                "monthly_savings": month_sav, 
                "target_monthly_expense": target_expense,
                "investment_style": inv_style,
                "monthly_shortfall_gap": gap,
                "readiness_score": score
            }

            assistant_container = st.chat_message("assistant")
            stream_placeholder = assistant_container.empty()

            async def _stream_advice():
                return await stream_advice(
                    current_stats,
                    st.session_state["advice_messages"],
                    st.session_state["current_lang"],
                    st.session_state["current_currency"],
                    on_token=lambda _delta, full: stream_placeholder.write(full),
                )

            response_text = asyncio.run(_stream_advice())

            st.session_state["advice_messages"].append(AIMessage(content=response_text))
            stream_placeholder.write(response_text)

    st.markdown("---")
    
    fc1, fc2 = st.columns([3, 1])
    
    with fc1:
        active_profile = {
            "age": age,
            "retirement_age": retire_age,
            "current_savings": curr_sav,
            "monthly_savings": month_sav,
            "target_monthly_expense": target_expense,
            "investment_style": inv_style
        }
        
        active_assumptions = {
            "rate": rate,
            "inflation": inflation,
            "growth": growth
        }
        
        report_html = generate_html_report(
            active_profile, active_assumptions, safe_income, target_expense, future_food, score, 
            st.session_state.get("advice_messages", []), 
            main_fig, st.session_state["current_lang"], st.session_state["current_currency"]
        )
        st.download_button(
            label=t["download_btn"],
            data=report_html,
            file_name="retirement_plan.html",
            mime="text/html",
            type="primary"
        )
        
    with fc2:
        if st.button(t["chat_again_btn"]):
            st.session_state["onboarding_complete"] = False
            st.rerun()
